### ISSUE TITLE
Allow safely converting from `Int32` to `Int`

### ISSUE THREAD

**Issue by tfausak** [tfausak/witch#26]
Technically `Int` is only guaranteed to have 29 (or is it 30?) bits of precision, so you can't safely convert from an `Int32` into an `Int` because it might overflow. However in practice that is almost never true. Most platforms have `Int`s that are the same size as `Int64`s. 

Witch could provide the proper instances using CPP, or perhaps something else. I think it would look like this:

``` hs
# if rangeOfInt >= rangeOfInt32
instance From Int32 Int where from = ...
# else
instance TryFrom Int32 Int where tryFrom = ...
# endif
```

**Comment by Mikolaj** [comment]
I'm the original complainer about the lack of safe conversion from Int32 to Int: yay, your library has found a potential bug (not really harmful in this case, but still) that int-cast has missed. I compile my code in GHCJS where Int is 32bit, so this type cast was unsafe, but int-cast didn't tell me that. So, CPP would be great, but for the time being the safe default is good enough.

**Comment by tfausak** [comment]
Ah, right! GHCJS. I should see if I can get that into the test suite.

**Comment by tfausak** [comment]
It might be easier to test using the [i386/ubuntu](https://hub.docker.com/r/i386/ubuntu/) Docker image than it would be to get GHCJS set up. But even on x86 `Int` has the same range as `Int32`:

``` hs
>>> maxBound :: Int
2147483647

>>> maxBound :: Int32
2147483647
```

**Comment by Mikolaj** [comment]
Oh really? Good to know. Still not sure about GHCJS, but it's probably the same.

**Comment by tfausak** [comment]
Apparently `Int`s are always at least 32 bits on GHC:

- https://stackoverflow.com/q/7786662/1274282
- https://hackage.haskell.org/package/ghc-prim-0.6.1/docs/GHC-Prim.html

> Haskell98 specifies that signed integers (type Int) must contain at least 30 bits. GHC always implements Int using the primitive type Int#, whose size equals the MachDeps.h constant WORD_SIZE_IN_BITS. This is normally set based on the config.h parameter SIZEOF_HSWORD, i.e., 32 bits on 32-bit machines, 64 bits on 64-bit machines. However, it can also be explicitly set to a smaller number than 64, e.g., 62 bits, to allow the possibility of using tag bits. Currently GHC itself has only 32-bit and 64-bit variants, but 61, 62, or 63-bit code can be exported as an external core file for use in other back ends. 30 and 31-bit code is no longer supported.

**Comment by tfausak** [comment]
32-bit support is going away in GHC 9.12: https://www.haskell.org/ghc/blog/20240613-32-bit-darwin-and-windows-deprecation.html
