### ISSUE TITLE
Laws?

### ISSUE THREAD

**Issue by 21it** [tfausak/witch#43]
It would be very nice to have a clear set of laws describing correct `From` and `TryFrom` instances. The biggest benefit I see is possibility of property-based tests for instances which can verify laws with QuickCheck. Another benefit is just guidance for developers to avoid confusion. Especially for developers working in a team, where arguments like "make sense", "feels right" and "is useful" are not working that great. Some examples of confusing instances:

```haskell
data City = City                 
  { cityName :: CityName,        
    cityPopulation :: Population 
  }                              
                                 
instance From City CityName where
  from = cityName                
                                 
data User = User                 
  { userName :: UserName,        
    userCity :: City             
  }                              
                                 
instance From User City where    
  from = userCity                
                                 
--                               
-- Maybe just use lens?          
--                               
instance From User CityName where
  from = via @City               
```

```haskell
newtype MoneyAmount                       
  = MoneyAmount (Ratio Natural)           
                                          
--                                        
-- Maybe we even write here all possible  
-- ways to parse Text (Read, FromJSON etc)
-- but is it right?                       
--                                        
instance TryFrom Text MoneyAmount where   
  tryFrom = undefined                     
```

```haskell
newtype OrderAmount                            
  = OrderAmount Rational                       
  deriving (Eq, Ord, Num)                      
                                               
data TradeAction = Buy | Sell                  
                                               
--                                             
-- Non injective, but is there an issue?       
--                                             
instance TryFrom OrderAmount TradeAction where 
  tryFrom x                                    
    | x > 0 = Right Buy                        
    | x < 0 = Right Sell                       
    | otherwise = Left failure                 
```

**Comment by tfausak** [comment]
I have struggled to come up with laws for Witch’s behavior. I’ve done my best to list some guidelines in the documentation: https://hackage.haskell.org/package/witch-0.3.4.1/docs/Witch.html#g:12

Specifically for your examples:

- I don’t often write instances that project some field of a record. I’d rather use a field selector or a lens. A similar instance that doesn’t depend on any custom types would be `instance From (a, b) a`. I don’t think that instance should exist because I wouldn’t be able to guess the behavior of the expression `from (1, 2)` without looking it up. Does it return `1` or `2`? 
- For conversions that “parse” the input, often I will choose a canonical representation to parse. But I feel like these can be as strict or lenient as you want. 
- I don’t expect `TryFrom` instances to be injective. I suspect there are many inputs that would output `Left _`. But if you restrict yourself to considering inputs that would output `Right _`, then yeah maybe those should be injective.

**Comment by 21it** [comment]
I have some thoughts about possible `From` and `TryFrom` laws, which I'm currently using in my own codebase:

1. `From a b` and `TryFrom a b` instances are mutually exclusive. For every existing `From a b` instance, `TryFrom a b` instance does not exist. For every existing `TryFrom a b` instance, `From a b` instance does not exist.

2. For every existing `From a b` instance, exists corresponding `From b a` or `TryFrom b a` instance (but not both because of 1st law). The same for every existing `TryFrom a b` instance - exists corresponding `From b a` or `TryFrom b a` instance. 

3. All instances do satisfy one of 3 equations:

```haskell
from @b @a . from @a @b = id

tryFrom @b @a . from @a @b = Right

-- if
isRight $ tryFrom @a @b x = True
-- then
tryFrom @a @b x >>= tryFrom @b @a = Right x 
```

**Comment by tfausak** [comment]
Ah, yes! Laws that involve multiple function calls are easier to come by. I agree with what you've proposed already. I'll restate them here in my own words/code:

``` hs
-- given
instance From A B

-- then *no*
instance TryFrom A B
```

``` hs
-- given
instance TryFrom A B

-- then *no*
instance From A B
```

``` hs
-- given
instance From A B

-- then either
instance From B A
-- or
instance TryFrom B A
```

``` hs
-- given
instance TryFrom A B

-- then either
instance From B A
-- or
instance TryFrom B A
```

``` hs
-- from . from
a |> from @A @B |> from @B @A == x

-- tryFrom . from
a |> from @A @B |> tryFrom @B @a == Right x

-- fmap from . tryFrom
case tryFrom @A @B a of
  Left _ -> True
  Right b -> from @B @A b == a

-- tryFrom <=< tryFrom
case tryFrom @A @B a of
  Left _ -> True
  Right b -> tryFrom @B @A b == Right a
```
