### ISSUE TITLE
suggestion: remove `over`

### ISSUE THREAD

**Issue by mitchellwrosen** [tfausak/witch#77]
Hey!

I see that `over` is defined in `Witch`, and exported from the main module. This means that if you want to use `witch` with `lens` or `optics`, you have to qualify one of them.

Personally, I only use `witch` for the principled type classes and basic conversions (`from`, `into`). I don't feel any of the other helpers cross the fairbairn threshold for me, but I'm happy to ignore them -- except for `over`, which clashes :)

Maybe we could instead hide `over` in `Witch.Utility`?

**Comment by tfausak** [comment]
Yeah, it's probably not worth being a default export. I haven't ended up using it as much as I thought I would. The `as` function is in a similar boat.

**Comment by tfausak** [comment]
Fixed by #82 and #83. Released as version [1.2.0.0](https://github.com/tfausak/witch/releases/tag/1.2.0.0).
